---
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /opt/mon/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=21d'
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - /opt/mon/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - grafana
    restart: always
  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    volumes:
      - /opt/mon/alertmanager/alertmanager.yml:/config/alertmanager.yml
    ports:
      - "9093:9093"
    command:
      - '--config.file=/config/alertmanager.yml'
    restart: always
  mktxp:
    image: ghcr.io/akpw/mktxp:latest
    container_name: mktxp
    user: root
    volumes:
      - /opt/mon/mktxp/:/root/mktxp/
    ports:
      - "49090:49090"
    restart: unless-stopped
  pve:
    image: prompve/prometheus-pve-exporter
    container_name: pve
    volumes:
      - /opt/mon/pve/pve.yml:/etc/prometheus/pve.yml
    ports:
      - "9221:9221"
    command:
      - '--config.file=/etc/prometheus/pve.yml'
    restart: unless-stopped
  speedtest:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest
    ports:
      - "9798:9798"
    restart: unless-stopped
  blackbox:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox
    volumes:
      - /opt/mon/blackbox/blackbox.yml:/config/blackbox.yml
    ports:
      - "9115:9115"
    command:
      - '--config.file=/config/blackbox.yml'
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
